name: Scheduled Pipeline

on:
  schedule:
    # Define the cron schedule for every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and test steps here
      - name: Build and Test
        run: |
          # Replace this with your build and test commands
          echo "Building and testing..."
